{
    "url": "https://api.github.com/repos/dask/dask/issues/7850",
    "repository_url": "https://api.github.com/repos/dask/dask",
    "labels_url": "https://api.github.com/repos/dask/dask/issues/7850/labels{/name}",
    "comments_url": "https://api.github.com/repos/dask/dask/issues/7850/comments",
    "events_url": "https://api.github.com/repos/dask/dask/issues/7850/events",
    "html_url": "https://github.com/dask/dask/issues/7850",
    "id": 933880312,
    "node_id": "MDU6SXNzdWU5MzM4ODAzMTI=",
    "number": 7850,
    "title": "Unable to load ORC table using `read_orc`",
    "user": {
        "login": "lucharo",
        "id": 47890755,
        "node_id": "MDQ6VXNlcjQ3ODkwNzU1",
        "avatar_url": "https://avatars.githubusercontent.com/u/47890755?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/lucharo",
        "html_url": "https://github.com/lucharo",
        "followers_url": "https://api.github.com/users/lucharo/followers",
        "following_url": "https://api.github.com/users/lucharo/following{/other_user}",
        "gists_url": "https://api.github.com/users/lucharo/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/lucharo/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/lucharo/subscriptions",
        "organizations_url": "https://api.github.com/users/lucharo/orgs",
        "repos_url": "https://api.github.com/users/lucharo/repos",
        "events_url": "https://api.github.com/users/lucharo/events{/privacy}",
        "received_events_url": "https://api.github.com/users/lucharo/received_events",
        "type": "User",
        "site_admin": false
    },
    "labels": [
        {
            "id": 242862289,
            "node_id": "MDU6TGFiZWwyNDI4NjIyODk=",
            "url": "https://api.github.com/repos/dask/dask/labels/dataframe",
            "name": "dataframe",
            "color": "fbca04",
            "default": false,
            "description": null
        },
        {
            "id": 365513534,
            "node_id": "MDU6TGFiZWwzNjU1MTM1MzQ=",
            "url": "https://api.github.com/repos/dask/dask/labels/io",
            "name": "io",
            "color": "6f871c",
            "default": false,
            "description": ""
        }
    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [],
    "milestone": null,
    "comments": 6,
    "created_at": "2021-06-30T16:17:03Z",
    "updated_at": "2021-07-22T19:26:03Z",
    "closed_at": null,
    "author_association": "NONE",
    "active_lock_reason": null,
    "body": "<!-- Please include a self-contained copy-pastable example that generates the issue if possible.\r\n\r\nPlease be concise with code posted. See guidelines below on how to provide a good bug report:\r\n\r\n- Craft Minimal Bug Reports http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports\r\n- Minimal Complete Verifiable Examples https://stackoverflow.com/help/mcve\r\n\r\nBug reports that follow these guidelines are easier to diagnose, and so are often handled much more quickly.\r\n-->\r\n\r\n**What happened**:\r\n\r\nI am trying to use `read_orc` to read an ORC table located in a Kerberised HDFS. I can use `read_parquet` but `read_orc` fails with the following attribute error:\r\n\r\n```py\r\n/projects/gds/chavesrl/condapv/envs/N2D/lib/python3.7/site-packages/dask/dataframe/io/orc.py in read_orc(path, columns, storage_options)\r\n     74                 raise ValueError(\"Incompatible schemas while parsing ORC files\")\r\n     75             nstripes_per_file.append(o.nstripes)\r\n---> 76     schema = _get_pyarrow_dtypes(schema, categories=None)\r\n     77     if columns is not None:\r\n     78         ex = set(columns) - set(schema)\r\n\r\n/projects/gds/chavesrl/condapv/envs/N2D/lib/python3.7/site-packages/dask/dataframe/io/utils.py in _get_pyarrow_dtypes(schema, categories)\r\n      9 \r\n     10     # Check for pandas metadata\r\n---> 11     has_pandas_metadata = schema.metadata is not None and b\"pandas\" in schema.metadata\r\n     12     if has_pandas_metadata:\r\n     13         pandas_metadata = json.loads(schema.metadata[b\"pandas\"].decode(\"utf8\"))\r\n\r\nAttributeError: 'NoneType' object has no attribute 'metadata'\r\n```\r\n\r\nafter running the following code:\r\n```py\r\nfrom dask.dataframe import read_orc\r\nread_orc(info['location']+'/*', \r\n         storage_options = {\r\n             'user':'{username}', \r\n             'kerb_ticket' : '/tmp/krb5cc_132855'\r\n         })\r\n```\r\nwhere `info['location']` is of the likes of: `hdfs://cluster/db/schema/table_name`\r\n\r\n\r\n**What you expected to happen**:\r\n\r\nTo have the table be loaded as a dask dataframe in the same way parquet tables are read succesfully\r\n\r\n**Anything else we need to know?**:\r\n\r\n**Environment**:\r\n\r\n- Dask version: '2021.04.0'\r\n- Python version: 3.7.10\r\n- Operating System: Linux RedHat\r\n- Install method (conda, pip, source): conda\r\n",
    "closed_by": null,
    "reactions": {
        "url": "https://api.github.com/repos/dask/dask/issues/7850/reactions",
        "total_count": 0,
        "+1": 0,
        "-1": 0,
        "laugh": 0,
        "hooray": 0,
        "confused": 0,
        "heart": 0,
        "rocket": 0,
        "eyes": 0
    },
    "timeline_url": "https://api.github.com/repos/dask/dask/issues/7850/timeline",
    "performed_via_github_app": null,
    "state_reason": null
}