{
    "url": "https://api.github.com/repos/dask/dask/issues/6275",
    "repository_url": "https://api.github.com/repos/dask/dask",
    "labels_url": "https://api.github.com/repos/dask/dask/issues/6275/labels{/name}",
    "comments_url": "https://api.github.com/repos/dask/dask/issues/6275/comments",
    "events_url": "https://api.github.com/repos/dask/dask/issues/6275/events",
    "html_url": "https://github.com/dask/dask/issues/6275",
    "id": 628716334,
    "node_id": "MDU6SXNzdWU2Mjg3MTYzMzQ=",
    "number": 6275,
    "title": "ones() and zeros() got multiple values for argument 'dtype'",
    "user": {
        "login": "bluegeo",
        "id": 19851732,
        "node_id": "MDQ6VXNlcjE5ODUxNzMy",
        "avatar_url": "https://avatars.githubusercontent.com/u/19851732?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/bluegeo",
        "html_url": "https://github.com/bluegeo",
        "followers_url": "https://api.github.com/users/bluegeo/followers",
        "following_url": "https://api.github.com/users/bluegeo/following{/other_user}",
        "gists_url": "https://api.github.com/users/bluegeo/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/bluegeo/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/bluegeo/subscriptions",
        "organizations_url": "https://api.github.com/users/bluegeo/orgs",
        "repos_url": "https://api.github.com/users/bluegeo/repos",
        "events_url": "https://api.github.com/users/bluegeo/events{/privacy}",
        "received_events_url": "https://api.github.com/users/bluegeo/received_events",
        "type": "User",
        "site_admin": false
    },
    "labels": [
        {
            "id": 242862305,
            "node_id": "MDU6TGFiZWwyNDI4NjIzMDU=",
            "url": "https://api.github.com/repos/dask/dask/labels/array",
            "name": "array",
            "color": "006b75",
            "default": false,
            "description": null
        }
    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [],
    "milestone": null,
    "comments": 4,
    "created_at": "2020-06-01T20:47:37Z",
    "updated_at": "2021-02-08T15:23:44Z",
    "closed_at": null,
    "author_association": "NONE",
    "active_lock_reason": null,
    "body": "While computing a dask array using the ones() (or zeros) API, and using `dtype` as a positional (second) argument, the following error occurs:\r\n\r\n```python\r\nTypeError: ones() got multiple values for argument 'dtype'\r\n```\r\n\r\nThe documentation states that they follow the signature of the numpy variants exactly, which would not require `dtype` to be a keyword argument.\r\n\r\nThis works:\r\n\r\n```python\r\nda.ones((3, 3), dtype='bool').compute()\r\n```\r\n\r\nBut this does not:\r\n\r\n```python\r\nda.ones((3, 3), 'bool').compute()\r\n```\r\n\r\nUsing dask-2.17.2-py_0 with Python 3.6.9 installed using conda on MacOS 10.15.5\r\n",
    "closed_by": null,
    "reactions": {
        "url": "https://api.github.com/repos/dask/dask/issues/6275/reactions",
        "total_count": 0,
        "+1": 0,
        "-1": 0,
        "laugh": 0,
        "hooray": 0,
        "confused": 0,
        "heart": 0,
        "rocket": 0,
        "eyes": 0
    },
    "timeline_url": "https://api.github.com/repos/dask/dask/issues/6275/timeline",
    "performed_via_github_app": null,
    "state_reason": null
}