{
    "url": "https://api.github.com/repos/dask/dask/issues/9663",
    "repository_url": "https://api.github.com/repos/dask/dask",
    "labels_url": "https://api.github.com/repos/dask/dask/issues/9663/labels{/name}",
    "comments_url": "https://api.github.com/repos/dask/dask/issues/9663/comments",
    "events_url": "https://api.github.com/repos/dask/dask/issues/9663/events",
    "html_url": "https://github.com/dask/dask/issues/9663",
    "id": 1450166974,
    "node_id": "I_kwDOAbcwm85Wb8q-",
    "number": 9663,
    "title": "Recursion error when submitting recursive object",
    "user": {
        "login": "charmoniumQ",
        "id": 928570,
        "node_id": "MDQ6VXNlcjkyODU3MA==",
        "avatar_url": "https://avatars.githubusercontent.com/u/928570?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/charmoniumQ",
        "html_url": "https://github.com/charmoniumQ",
        "followers_url": "https://api.github.com/users/charmoniumQ/followers",
        "following_url": "https://api.github.com/users/charmoniumQ/following{/other_user}",
        "gists_url": "https://api.github.com/users/charmoniumQ/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/charmoniumQ/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/charmoniumQ/subscriptions",
        "organizations_url": "https://api.github.com/users/charmoniumQ/orgs",
        "repos_url": "https://api.github.com/users/charmoniumQ/repos",
        "events_url": "https://api.github.com/users/charmoniumQ/events{/privacy}",
        "received_events_url": "https://api.github.com/users/charmoniumQ/received_events",
        "type": "User",
        "site_admin": false
    },
    "labels": [
        {
            "id": 386719400,
            "node_id": "MDU6TGFiZWwzODY3MTk0MDA=",
            "url": "https://api.github.com/repos/dask/dask/labels/scheduler",
            "name": "scheduler",
            "color": "D10945",
            "default": false,
            "description": ""
        },
        {
            "id": 3468123446,
            "node_id": "LA_kwDOAbcwm87Ot102",
            "url": "https://api.github.com/repos/dask/dask/labels/needs%20attention",
            "name": "needs attention",
            "color": "6d626c",
            "default": false,
            "description": "It's been a while since this was pushed on. Needs attention from the owner or a maintainer."
        },
        {
            "id": 3798450413,
            "node_id": "LA_kwDOAbcwm87iZ8Dt",
            "url": "https://api.github.com/repos/dask/dask/labels/bug",
            "name": "bug",
            "color": "faadaf",
            "default": true,
            "description": "Something is broken"
        }
    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [],
    "milestone": null,
    "comments": 1,
    "created_at": "2022-11-15T17:56:17Z",
    "updated_at": "2022-12-19T01:54:51Z",
    "closed_at": null,
    "author_association": "CONTRIBUTOR",
    "active_lock_reason": null,
    "body": "**Describe the issue**:\r\n\r\nWhen I submit an object that recurses in a specific way, it causes Dask to infinitely recurse.\r\n\r\n```python\r\nimport dask.distributed\r\nfrom dataclasses import dataclass\r\nfrom typing import Any\r\n\r\n@dataclasses\r\nclass Node:\r\n    next: Any = None\r\n    prev: Any = None\r\n\r\na = Node()\r\nb = Node()\r\nc = Node()\r\na.next = b\r\nb.next = c\r\nc.prev = b\r\nb.prev = a\r\n\r\nwith dask.distributed.LocalCluster() as cluster, dask.distributed.Client(cluster) as client:\r\n    client.submit(print, a)\r\n```\r\n\r\n**Error summary:** The program says `Exception ignored ... RecursionError`. It presumably retries, because it prints that same error every few seconds until I hit ctrl+c, at which point I get a KeyboardInterrupt traceback.\r\n\r\n1. `test.py:19`, which reads `client.submit(print, a)`\r\n2. `distributed/client.py:1836:submit`\r\n3. `dask/base.py:931:tokenize`\r\n4. `dask/utils.py:640:__call__` (recursion returns to this frame)\r\n4. `dask/base.py:1020:normalize_object`\r\n5. `dask/base.py:1094:normalize_dataclass`\r\n6. `dask/base.py:978:_normalize_seq_func`\r\n7. `dask/utils.py:640:__call__`\r\n8. `dask/base.py:992:normalize_seq`\r\n9. `dask/base.py:978:_normalize_seq_func`\r\n10. back to 4\r\n\r\nFull error log: [here](https://hastebin.com/cejeyotolo.kotlin)\r\n\r\n**Anything else we need to know?**:\r\n\r\nI've tried whittling this down further, but it appears it requires all three nodes, all four links, and it must be a `@dataclass`. This at least means that the client is robust to _some kinds of_ recursion, just not this specific configuration.\r\n\r\nAll of this, just to name the future (distributed/client.py:1836). It seems like if Dask could get past naming it, the rest would work fine. The object is perfectly `cloudpickle`-able.\r\n\r\n**Environment**:\r\n\r\n- Dask version: 2022.10.2\r\n- Python version: 3.10.6\r\n- Operating System: Ubuntu 22.04.1 LTS\r\n- Install method (conda, pip, source): pip/poetry",
    "closed_by": null,
    "reactions": {
        "url": "https://api.github.com/repos/dask/dask/issues/9663/reactions",
        "total_count": 0,
        "+1": 0,
        "-1": 0,
        "laugh": 0,
        "hooray": 0,
        "confused": 0,
        "heart": 0,
        "rocket": 0,
        "eyes": 0
    },
    "timeline_url": "https://api.github.com/repos/dask/dask/issues/9663/timeline",
    "performed_via_github_app": null,
    "state_reason": null
}