{
    "url": "https://api.github.com/repos/dask/dask/issues/8877",
    "repository_url": "https://api.github.com/repos/dask/dask",
    "labels_url": "https://api.github.com/repos/dask/dask/issues/8877/labels{/name}",
    "comments_url": "https://api.github.com/repos/dask/dask/issues/8877/comments",
    "events_url": "https://api.github.com/repos/dask/dask/issues/8877/events",
    "html_url": "https://github.com/dask/dask/issues/8877",
    "id": 1190289111,
    "node_id": "I_kwDOAbcwm85G8l7X",
    "number": 8877,
    "title": "Windows distributed tests - periodic `PermissionError`",
    "user": {
        "login": "jcrist",
        "id": 2783717,
        "node_id": "MDQ6VXNlcjI3ODM3MTc=",
        "avatar_url": "https://avatars.githubusercontent.com/u/2783717?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/jcrist",
        "html_url": "https://github.com/jcrist",
        "followers_url": "https://api.github.com/users/jcrist/followers",
        "following_url": "https://api.github.com/users/jcrist/following{/other_user}",
        "gists_url": "https://api.github.com/users/jcrist/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/jcrist/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/jcrist/subscriptions",
        "organizations_url": "https://api.github.com/users/jcrist/orgs",
        "repos_url": "https://api.github.com/users/jcrist/repos",
        "events_url": "https://api.github.com/users/jcrist/events{/privacy}",
        "received_events_url": "https://api.github.com/users/jcrist/received_events",
        "type": "User",
        "site_admin": false
    },
    "labels": [
        {
            "id": 1887344368,
            "node_id": "MDU6TGFiZWwxODg3MzQ0MzY4",
            "url": "https://api.github.com/repos/dask/dask/labels/tests",
            "name": "tests",
            "color": "a0f9b4",
            "default": false,
            "description": "Unit tests and/or continuous integration"
        },
        {
            "id": 3468123446,
            "node_id": "LA_kwDOAbcwm87Ot102",
            "url": "https://api.github.com/repos/dask/dask/labels/needs%20attention",
            "name": "needs attention",
            "color": "6d626c",
            "default": false,
            "description": "It's been a while since this was pushed on. Needs attention from the owner or a maintainer."
        }
    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [],
    "milestone": null,
    "comments": 2,
    "created_at": "2022-04-01T21:29:10Z",
    "updated_at": "2022-05-09T02:12:50Z",
    "closed_at": null,
    "author_association": "MEMBER",
    "active_lock_reason": null,
    "body": "We started seeing periodic `PermissionError`s in the `test_distributed.py` tests a few days ago. Example failure in https://github.com/dask/dask/runs/5793620996?check_suite_focus=true#step:6:21867.\r\n\r\n```\r\n=================================== ERRORS ====================================\r\n________ ERROR at teardown of test_blockwise_array_creation[None-ones] ________\r\n[gw2] win32 -- Python 3.10.4 C:\\Miniconda3\\envs\\test-environment\\python.exe\r\n\r\nloop = <tornado.platform.asyncio.AsyncIOLoop object at 0x000001FB03165690>\r\n\r\n    @pytest.fixture\r\n    def cluster_fixture(loop):\r\n>       with cluster() as (scheduler, workers):\r\n\r\nC:\\Miniconda3\\envs\\test-environment\\lib\\site-packages\\distributed\\utils_test.py:538: \r\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\r\nC:\\Miniconda3\\envs\\test-environment\\lib\\contextlib.py:142: in __exit__\r\n    next(self.gen)\r\nC:\\Miniconda3\\envs\\test-environment\\lib\\site-packages\\distributed\\utils_test.py:654: in cluster\r\n    with contextlib.ExitStack() as stack:\r\nC:\\Miniconda3\\envs\\test-environment\\lib\\contextlib.py:576: in __exit__\r\n    raise exc_details[1]\r\nC:\\Miniconda3\\envs\\test-environment\\lib\\contextlib.py:561: in __exit__\r\n    if cb(*exc_details):\r\nC:\\Miniconda3\\envs\\test-environment\\lib\\contextlib.py:449: in _exit_wrapper\r\n    callback(*args, **kwds)\r\nC:\\Miniconda3\\envs\\test-environment\\lib\\site-packages\\distributed\\utils_test.py:611: in _terminate_join\r\n    proc.terminate()\r\nC:\\Miniconda3\\envs\\test-environment\\lib\\multiprocessing\\process.py:133: in terminate\r\n    self._popen.terminate()\r\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\r\n\r\nself = <multiprocessing.popen_spawn_win32.Popen object at 0x000001FB0316AEF0>\r\n\r\n    def terminate(self):\r\n        if self.returncode is None:\r\n            try:\r\n>               _winapi.TerminateProcess(int(self._handle), TERMINATE)\r\nE               PermissionError: [WinError 5] Access is denied\r\n\r\nC:\\Miniconda3\\envs\\test-environment\\lib\\multiprocessing\\popen_spawn_win32.py:123: PermissionError\r\n```",
    "closed_by": null,
    "reactions": {
        "url": "https://api.github.com/repos/dask/dask/issues/8877/reactions",
        "total_count": 0,
        "+1": 0,
        "-1": 0,
        "laugh": 0,
        "hooray": 0,
        "confused": 0,
        "heart": 0,
        "rocket": 0,
        "eyes": 0
    },
    "timeline_url": "https://api.github.com/repos/dask/dask/issues/8877/timeline",
    "performed_via_github_app": null,
    "state_reason": null
}