{
    "url": "https://api.github.com/repos/dask/dask/issues/9401",
    "repository_url": "https://api.github.com/repos/dask/dask",
    "labels_url": "https://api.github.com/repos/dask/dask/issues/9401/labels{/name}",
    "comments_url": "https://api.github.com/repos/dask/dask/issues/9401/comments",
    "events_url": "https://api.github.com/repos/dask/dask/issues/9401/events",
    "html_url": "https://github.com/dask/dask/issues/9401",
    "id": 1342822793,
    "node_id": "I_kwDOAbcwm85QCdmJ",
    "number": 9401,
    "title": "Dask Dataframe does not support Pandas dtype 'Float32'",
    "user": {
        "login": "Tishj",
        "id": 17162323,
        "node_id": "MDQ6VXNlcjE3MTYyMzIz",
        "avatar_url": "https://avatars.githubusercontent.com/u/17162323?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/Tishj",
        "html_url": "https://github.com/Tishj",
        "followers_url": "https://api.github.com/users/Tishj/followers",
        "following_url": "https://api.github.com/users/Tishj/following{/other_user}",
        "gists_url": "https://api.github.com/users/Tishj/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/Tishj/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/Tishj/subscriptions",
        "organizations_url": "https://api.github.com/users/Tishj/orgs",
        "repos_url": "https://api.github.com/users/Tishj/repos",
        "events_url": "https://api.github.com/users/Tishj/events{/privacy}",
        "received_events_url": "https://api.github.com/users/Tishj/received_events",
        "type": "User",
        "site_admin": false
    },
    "labels": [
        {
            "id": 242862305,
            "node_id": "MDU6TGFiZWwyNDI4NjIzMDU=",
            "url": "https://api.github.com/repos/dask/dask/labels/array",
            "name": "array",
            "color": "006b75",
            "default": false,
            "description": null
        },
        {
            "id": 365513534,
            "node_id": "MDU6TGFiZWwzNjU1MTM1MzQ=",
            "url": "https://api.github.com/repos/dask/dask/labels/io",
            "name": "io",
            "color": "6f871c",
            "default": false,
            "description": ""
        },
        {
            "id": 1887344368,
            "node_id": "MDU6TGFiZWwxODg3MzQ0MzY4",
            "url": "https://api.github.com/repos/dask/dask/labels/tests",
            "name": "tests",
            "color": "a0f9b4",
            "default": false,
            "description": "Unit tests and/or continuous integration"
        },
        {
            "id": 3468123446,
            "node_id": "LA_kwDOAbcwm87Ot102",
            "url": "https://api.github.com/repos/dask/dask/labels/needs%20attention",
            "name": "needs attention",
            "color": "6d626c",
            "default": false,
            "description": "It's been a while since this was pushed on. Needs attention from the owner or a maintainer."
        }
    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [],
    "milestone": null,
    "comments": 4,
    "created_at": "2022-08-18T09:24:15Z",
    "updated_at": "2024-06-03T01:49:03Z",
    "closed_at": null,
    "author_association": "NONE",
    "active_lock_reason": null,
    "body": "```py\r\npd_df = pd.DataFrame({\r\n\t\t'float32': pd.Series([None, 1, 4294967295], dtype=\"Float32\"),\r\n\t\t'float64': pd.Series([None, 1, 18446744073709551615], dtype=\"Float64\")}\r\n)\r\n\r\ndd_df = dd.from_pandas(pd_df, npartitions=10)\r\nprint(dd_df['float32'].values)\r\n# This last line caused the crash\r\n```\r\n\r\n**What happened**:\r\n```\r\nTraceback (most recent call last):\r\n  File \"dask_test.py\", line 17, in <module>\r\n    print(dd_df['float32'].values)\r\n  File \"/opt/homebrew/lib/python3.9/site-packages/dask/dataframe/core.py\", line 3324, in values\r\n    return self.map_partitions(methods.values)\r\n  File \"/opt/homebrew/lib/python3.9/site-packages/dask/dataframe/core.py\", line 867, in map_partitions\r\n    return map_partitions(func, self, *args, **kwargs)\r\n  File \"/opt/homebrew/lib/python3.9/site-packages/dask/dataframe/core.py\", line 6578, in map_partitions\r\n    return new_dd_object(graph, name, meta, divisions)\r\n  File \"/opt/homebrew/lib/python3.9/site-packages/dask/dataframe/core.py\", line 7706, in new_dd_object\r\n    return da.Array(dsk, name=name, chunks=chunks, dtype=meta.dtype)\r\n  File \"/opt/homebrew/lib/python3.9/site-packages/dask/array/core.py\", line 1329, in __new__\r\n    meta = meta_from_array(meta, dtype=dtype)\r\n  File \"/opt/homebrew/lib/python3.9/site-packages/dask/array/utils.py\", line 57, in meta_from_array\r\n    x = x(shape=(0,) * (ndim or 0), dtype=dtype)\r\nTypeError: Cannot interpret 'Float32Dtype()' as a data type\r\n```\r\n\r\n**What you expected to happen**:\r\nI would expect the either `from_pandas` to fail instantly, or for it to be able to work with the dtype\r\n\r\n**Anything else we need to know?**:\r\n\r\n**Environment**:\r\n\r\n- Dask version: installed through `python3 -m pip install dask`\r\n```py\r\n>>> dask._version.version_json\r\n'\\n{\\n \"dirty\": false,\\n \"error\": null,\\n \"full-revisionid\": \"a77ce9513745d64cb47033d5f8026b3acc5424bf\",\\n \"version\": \"2022.8.0\"\\n}\\n'\r\n```\r\n- Python version: 3.9.13\r\n- Operating System: MacOS\r\n- Install method (conda, pip, source): pip",
    "closed_by": null,
    "reactions": {
        "url": "https://api.github.com/repos/dask/dask/issues/9401/reactions",
        "total_count": 0,
        "+1": 0,
        "-1": 0,
        "laugh": 0,
        "hooray": 0,
        "confused": 0,
        "heart": 0,
        "rocket": 0,
        "eyes": 0
    },
    "timeline_url": "https://api.github.com/repos/dask/dask/issues/9401/timeline",
    "performed_via_github_app": null,
    "state_reason": null
}