{
    "url": "https://api.github.com/repos/dask/dask/issues/10683",
    "repository_url": "https://api.github.com/repos/dask/dask",
    "labels_url": "https://api.github.com/repos/dask/dask/issues/10683/labels{/name}",
    "comments_url": "https://api.github.com/repos/dask/dask/issues/10683/comments",
    "events_url": "https://api.github.com/repos/dask/dask/issues/10683/events",
    "html_url": "https://github.com/dask/dask/issues/10683",
    "id": 2032964007,
    "node_id": "I_kwDOAbcwm855LJGn",
    "number": 10683,
    "title": "Unexpected Results Caused by BigInt ID in numpy linspace",
    "user": {
        "login": "hungtn1297",
        "id": 56312980,
        "node_id": "MDQ6VXNlcjU2MzEyOTgw",
        "avatar_url": "https://avatars.githubusercontent.com/u/56312980?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/hungtn1297",
        "html_url": "https://github.com/hungtn1297",
        "followers_url": "https://api.github.com/users/hungtn1297/followers",
        "following_url": "https://api.github.com/users/hungtn1297/following{/other_user}",
        "gists_url": "https://api.github.com/users/hungtn1297/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/hungtn1297/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/hungtn1297/subscriptions",
        "organizations_url": "https://api.github.com/users/hungtn1297/orgs",
        "repos_url": "https://api.github.com/users/hungtn1297/repos",
        "events_url": "https://api.github.com/users/hungtn1297/events{/privacy}",
        "received_events_url": "https://api.github.com/users/hungtn1297/received_events",
        "type": "User",
        "site_admin": false
    },
    "labels": [
        {
            "id": 1342320181,
            "node_id": "MDU6TGFiZWwxMzQyMzIwMTgx",
            "url": "https://api.github.com/repos/dask/dask/labels/needs%20info",
            "name": "needs info",
            "color": "d0cfcc",
            "default": false,
            "description": "Needs further information from the user"
        }
    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [],
    "milestone": null,
    "comments": 1,
    "created_at": "2023-12-08T16:22:09Z",
    "updated_at": "2023-12-12T11:55:11Z",
    "closed_at": null,
    "author_association": "NONE",
    "active_lock_reason": null,
    "body": "https://github.com/dask/dask/blob/191d39177009d2cce25b818878118e35329b6db3/dask/dataframe/io/sql.py#L171-L172\r\n\r\nThere is an issue with the **np.linspace** function when the values of **maxi** and **mini** are too large (for example, 23849864652850694). It returns an unexpected value, which causes the SQL conditions to be incorrect.\r\n\r\n\r\nPlease check the example below\r\n```\r\n# Please use this code in the terminal to see the result\r\nimport numpy as np\r\n\r\nnp.linspace(23849864652850694, 23849864652850694, 2, dtype=np.int64).tolist()\r\n# expected [23849864652850694, 23849864652850694]\r\n# result   [23849864652850696, 23849864652850696]\r\n```",
    "closed_by": null,
    "reactions": {
        "url": "https://api.github.com/repos/dask/dask/issues/10683/reactions",
        "total_count": 0,
        "+1": 0,
        "-1": 0,
        "laugh": 0,
        "hooray": 0,
        "confused": 0,
        "heart": 0,
        "rocket": 0,
        "eyes": 0
    },
    "timeline_url": "https://api.github.com/repos/dask/dask/issues/10683/timeline",
    "performed_via_github_app": null,
    "state_reason": null
}