[
    {
        "url": "https://api.github.com/repos/dask/dask/issues/comments/886810649",
        "html_url": "https://github.com/dask/dask/issues/7926#issuecomment-886810649",
        "issue_url": "https://api.github.com/repos/dask/dask/issues/7926",
        "id": 886810649,
        "node_id": "IC_kwDOAbcwm84026gZ",
        "user": {
            "login": "jsignell",
            "id": 4806877,
            "node_id": "MDQ6VXNlcjQ4MDY4Nzc=",
            "avatar_url": "https://avatars.githubusercontent.com/u/4806877?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/jsignell",
            "html_url": "https://github.com/jsignell",
            "followers_url": "https://api.github.com/users/jsignell/followers",
            "following_url": "https://api.github.com/users/jsignell/following{/other_user}",
            "gists_url": "https://api.github.com/users/jsignell/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/jsignell/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/jsignell/subscriptions",
            "organizations_url": "https://api.github.com/users/jsignell/orgs",
            "repos_url": "https://api.github.com/users/jsignell/repos",
            "events_url": "https://api.github.com/users/jsignell/events{/privacy}",
            "received_events_url": "https://api.github.com/users/jsignell/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2021-07-26T15:37:34Z",
        "updated_at": "2021-07-26T15:37:34Z",
        "author_association": "MEMBER",
        "body": "Thanks for opening this @N4321D. @martindurant do you have any ideas about this one?",
        "reactions": {
            "url": "https://api.github.com/repos/dask/dask/issues/comments/886810649/reactions",
            "total_count": 1,
            "+1": 1,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/dask/dask/issues/comments/886823901",
        "html_url": "https://github.com/dask/dask/issues/7926#issuecomment-886823901",
        "issue_url": "https://api.github.com/repos/dask/dask/issues/7926",
        "id": 886823901,
        "node_id": "IC_kwDOAbcwm84029vd",
        "user": {
            "login": "martindurant",
            "id": 6042212,
            "node_id": "MDQ6VXNlcjYwNDIyMTI=",
            "avatar_url": "https://avatars.githubusercontent.com/u/6042212?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/martindurant",
            "html_url": "https://github.com/martindurant",
            "followers_url": "https://api.github.com/users/martindurant/followers",
            "following_url": "https://api.github.com/users/martindurant/following{/other_user}",
            "gists_url": "https://api.github.com/users/martindurant/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/martindurant/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/martindurant/subscriptions",
            "organizations_url": "https://api.github.com/users/martindurant/orgs",
            "repos_url": "https://api.github.com/users/martindurant/repos",
            "events_url": "https://api.github.com/users/martindurant/events{/privacy}",
            "received_events_url": "https://api.github.com/users/martindurant/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2021-07-26T15:55:29Z",
        "updated_at": "2021-07-26T16:16:12Z",
        "author_association": "MEMBER",
        "body": "There are *loads* of issues related to hdf5 writing across processes (e.g., https://github.com/dask/dask/issues/3074 and all the links therein). I can confirm that I also see the exception, even when explicitly providing a distributed lock. I ran a quick test and I can see that a lock (a `SerializableLock`) is indeed making its way into `dask.dataframe.io.hdf._pd_to_hdf`: \r\n```python\r\ndef _pd_to_hdf(pd_to_hdf, lock, args, kwargs=None):\r\n    \"\"\"A wrapper function around pd_to_hdf that enables locking\"\"\"\r\n\r\n    if lock:\r\n        lock.acquire()\r\n    try:\r\n        print(\"#### LOCK: \", lock)\r\n        pd_to_hdf(*args, **kwargs)\r\n    finally:\r\n        if lock:\r\n            lock.release()\r\n\r\n    return None\r\n```",
        "reactions": {
            "url": "https://api.github.com/repos/dask/dask/issues/comments/886823901/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    }
]