[
    {
        "url": "https://api.github.com/repos/dask/dask/issues/comments/564136109",
        "html_url": "https://github.com/dask/dask/pull/5686#issuecomment-564136109",
        "issue_url": "https://api.github.com/repos/dask/dask/issues/5686",
        "id": 564136109,
        "node_id": "MDEyOklzc3VlQ29tbWVudDU2NDEzNjEwOQ==",
        "user": {
            "login": "TomAugspurger",
            "id": 1312546,
            "node_id": "MDQ6VXNlcjEzMTI1NDY=",
            "avatar_url": "https://avatars.githubusercontent.com/u/1312546?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/TomAugspurger",
            "html_url": "https://github.com/TomAugspurger",
            "followers_url": "https://api.github.com/users/TomAugspurger/followers",
            "following_url": "https://api.github.com/users/TomAugspurger/following{/other_user}",
            "gists_url": "https://api.github.com/users/TomAugspurger/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/TomAugspurger/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/TomAugspurger/subscriptions",
            "organizations_url": "https://api.github.com/users/TomAugspurger/orgs",
            "repos_url": "https://api.github.com/users/TomAugspurger/repos",
            "events_url": "https://api.github.com/users/TomAugspurger/events{/privacy}",
            "received_events_url": "https://api.github.com/users/TomAugspurger/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2019-12-10T17:13:09Z",
        "updated_at": "2019-12-10T17:22:05Z",
        "author_association": "MEMBER",
        "body": "I'm not sure what to do about `errors=\"ignore\"` here, since it potentially makes our metadata incorrect. My initial preference is to include the keyword for compatibility, but raise if anything other than the default of `errors=\"raise\"` is passed with a nice explanation about why it's not supported.\r\n\r\n```python\r\nif errors != \"raise\":\r\n    raise ValueError(\"Only `errors='raise'` is supported. `errors='ignore' cannot be supported because the dtype of the output depends on the values present in the data. Use `to_numeric` instead.\r\n```\r\n\r\nOpened https://github.com/dask/dask/issues/5698 for implementing dask.dataframe.to_numeric.",
        "reactions": {
            "url": "https://api.github.com/repos/dask/dask/issues/comments/564136109/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/dask/dask/issues/comments/566094604",
        "html_url": "https://github.com/dask/dask/pull/5686#issuecomment-566094604",
        "issue_url": "https://api.github.com/repos/dask/dask/issues/5686",
        "id": 566094604,
        "node_id": "MDEyOklzc3VlQ29tbWVudDU2NjA5NDYwNA==",
        "user": {
            "login": "TomAugspurger",
            "id": 1312546,
            "node_id": "MDQ6VXNlcjEzMTI1NDY=",
            "avatar_url": "https://avatars.githubusercontent.com/u/1312546?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/TomAugspurger",
            "html_url": "https://github.com/TomAugspurger",
            "followers_url": "https://api.github.com/users/TomAugspurger/followers",
            "following_url": "https://api.github.com/users/TomAugspurger/following{/other_user}",
            "gists_url": "https://api.github.com/users/TomAugspurger/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/TomAugspurger/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/TomAugspurger/subscriptions",
            "organizations_url": "https://api.github.com/users/TomAugspurger/orgs",
            "repos_url": "https://api.github.com/users/TomAugspurger/repos",
            "events_url": "https://api.github.com/users/TomAugspurger/events{/privacy}",
            "received_events_url": "https://api.github.com/users/TomAugspurger/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2019-12-16T14:53:25Z",
        "updated_at": "2019-12-16T14:53:25Z",
        "author_association": "MEMBER",
        "body": "@zacharylawrence do you have an opinion on https://github.com/dask/dask/pull/5686#issuecomment-564136109?\r\n\r\nOne option would be to essentially assume that the `astype` fails and convert to the fallback option. So `.astype(\"float\", errors=\"ignore\")` would translate to a pandas `.astype(\"float', errors=\"ignore\").astype(object)`. I'm not sure about that either though.",
        "reactions": {
            "url": "https://api.github.com/repos/dask/dask/issues/comments/566094604/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/dask/dask/issues/comments/596758937",
        "html_url": "https://github.com/dask/dask/pull/5686#issuecomment-596758937",
        "issue_url": "https://api.github.com/repos/dask/dask/issues/5686",
        "id": 596758937,
        "node_id": "MDEyOklzc3VlQ29tbWVudDU5Njc1ODkzNw==",
        "user": {
            "login": "TomAugspurger",
            "id": 1312546,
            "node_id": "MDQ6VXNlcjEzMTI1NDY=",
            "avatar_url": "https://avatars.githubusercontent.com/u/1312546?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/TomAugspurger",
            "html_url": "https://github.com/TomAugspurger",
            "followers_url": "https://api.github.com/users/TomAugspurger/followers",
            "following_url": "https://api.github.com/users/TomAugspurger/following{/other_user}",
            "gists_url": "https://api.github.com/users/TomAugspurger/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/TomAugspurger/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/TomAugspurger/subscriptions",
            "organizations_url": "https://api.github.com/users/TomAugspurger/orgs",
            "repos_url": "https://api.github.com/users/TomAugspurger/repos",
            "events_url": "https://api.github.com/users/TomAugspurger/events{/privacy}",
            "received_events_url": "https://api.github.com/users/TomAugspurger/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2020-03-09T20:19:30Z",
        "updated_at": "2020-03-09T20:19:30Z",
        "author_association": "MEMBER",
        "body": "What's the status here @zacharylawrence? I think there's a pending discussion in https://github.com/dask/dask/pull/5686#issuecomment-564136109.\r\n\r\nNote that `dd.to_numeric` has been merged in the meantime, with support for just `errors={'raise', 'coerce'}`.",
        "reactions": {
            "url": "https://api.github.com/repos/dask/dask/issues/comments/596758937/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    }
]