[
    {
        "url": "https://api.github.com/repos/dask/dask/issues/comments/1252167431",
        "html_url": "https://github.com/dask/dask/pull/9506#issuecomment-1252167431",
        "issue_url": "https://api.github.com/repos/dask/dask/issues/9506",
        "id": 1252167431,
        "node_id": "IC_kwDOAbcwm85Koo8H",
        "user": {
            "login": "GPUtester",
            "id": 38199262,
            "node_id": "MDQ6VXNlcjM4MTk5MjYy",
            "avatar_url": "https://avatars.githubusercontent.com/u/38199262?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/GPUtester",
            "html_url": "https://github.com/GPUtester",
            "followers_url": "https://api.github.com/users/GPUtester/followers",
            "following_url": "https://api.github.com/users/GPUtester/following{/other_user}",
            "gists_url": "https://api.github.com/users/GPUtester/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/GPUtester/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/GPUtester/subscriptions",
            "organizations_url": "https://api.github.com/users/GPUtester/orgs",
            "repos_url": "https://api.github.com/users/GPUtester/repos",
            "events_url": "https://api.github.com/users/GPUtester/events{/privacy}",
            "received_events_url": "https://api.github.com/users/GPUtester/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2022-09-20T10:41:00Z",
        "updated_at": "2022-09-20T10:41:00Z",
        "author_association": "COLLABORATOR",
        "body": "Can one of the admins verify this patch?\n\nAdmins can comment `ok to test` to allow this one PR to run or `add to allowlist` to allow all future PRs from the same author to run.",
        "reactions": {
            "url": "https://api.github.com/repos/dask/dask/issues/comments/1252167431/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/dask/dask/issues/comments/1252193688",
        "html_url": "https://github.com/dask/dask/pull/9506#issuecomment-1252193688",
        "issue_url": "https://api.github.com/repos/dask/dask/issues/9506",
        "id": 1252193688,
        "node_id": "IC_kwDOAbcwm85KovWY",
        "user": {
            "login": "marberi",
            "id": 2119690,
            "node_id": "MDQ6VXNlcjIxMTk2OTA=",
            "avatar_url": "https://avatars.githubusercontent.com/u/2119690?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/marberi",
            "html_url": "https://github.com/marberi",
            "followers_url": "https://api.github.com/users/marberi/followers",
            "following_url": "https://api.github.com/users/marberi/following{/other_user}",
            "gists_url": "https://api.github.com/users/marberi/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/marberi/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/marberi/subscriptions",
            "organizations_url": "https://api.github.com/users/marberi/orgs",
            "repos_url": "https://api.github.com/users/marberi/repos",
            "events_url": "https://api.github.com/users/marberi/events{/privacy}",
            "received_events_url": "https://api.github.com/users/marberi/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2022-09-20T11:06:08Z",
        "updated_at": "2022-09-20T11:06:08Z",
        "author_association": "NONE",
        "body": "@jakirkham ",
        "reactions": {
            "url": "https://api.github.com/repos/dask/dask/issues/comments/1252193688/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/dask/dask/issues/comments/1252768720",
        "html_url": "https://github.com/dask/dask/pull/9506#issuecomment-1252768720",
        "issue_url": "https://api.github.com/repos/dask/dask/issues/9506",
        "id": 1252768720,
        "node_id": "IC_kwDOAbcwm85Kq7vQ",
        "user": {
            "login": "phobson",
            "id": 1163939,
            "node_id": "MDQ6VXNlcjExNjM5Mzk=",
            "avatar_url": "https://avatars.githubusercontent.com/u/1163939?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/phobson",
            "html_url": "https://github.com/phobson",
            "followers_url": "https://api.github.com/users/phobson/followers",
            "following_url": "https://api.github.com/users/phobson/following{/other_user}",
            "gists_url": "https://api.github.com/users/phobson/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/phobson/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/phobson/subscriptions",
            "organizations_url": "https://api.github.com/users/phobson/orgs",
            "repos_url": "https://api.github.com/users/phobson/repos",
            "events_url": "https://api.github.com/users/phobson/events{/privacy}",
            "received_events_url": "https://api.github.com/users/phobson/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2022-09-20T18:44:54Z",
        "updated_at": "2022-09-20T18:45:54Z",
        "author_association": "MEMBER",
        "body": "@marberi thanks for the PR and the test.\r\n\r\nBased on my understanding of the underlying issue, I'd expect this to fail. Indeed, when I run it locally in isolation (not a part of the larger suite), it fails by raising and error related to mult-indexes.\r\n\r\nIs your intent here to show/confirm/document that multi-indexes are not supported? If so, we should decorate the tests with an xfail mark. Something like:\r\n\r\n```python\r\n@pytest.mark.xfail(reason=\"Multi-indexes are not supported\", raises=ValueError)\r\n```\r\n\r\nDoes that make sense? Is this your intention with this PR?",
        "reactions": {
            "url": "https://api.github.com/repos/dask/dask/issues/comments/1252768720/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/dask/dask/issues/comments/1252826719",
        "html_url": "https://github.com/dask/dask/pull/9506#issuecomment-1252826719",
        "issue_url": "https://api.github.com/repos/dask/dask/issues/9506",
        "id": 1252826719,
        "node_id": "IC_kwDOAbcwm85KrJ5f",
        "user": {
            "login": "marberi",
            "id": 2119690,
            "node_id": "MDQ6VXNlcjIxMTk2OTA=",
            "avatar_url": "https://avatars.githubusercontent.com/u/2119690?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/marberi",
            "html_url": "https://github.com/marberi",
            "followers_url": "https://api.github.com/users/marberi/followers",
            "following_url": "https://api.github.com/users/marberi/following{/other_user}",
            "gists_url": "https://api.github.com/users/marberi/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/marberi/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/marberi/subscriptions",
            "organizations_url": "https://api.github.com/users/marberi/orgs",
            "repos_url": "https://api.github.com/users/marberi/repos",
            "events_url": "https://api.github.com/users/marberi/events{/privacy}",
            "received_events_url": "https://api.github.com/users/marberi/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2022-09-20T19:44:36Z",
        "updated_at": "2022-09-20T19:44:36Z",
        "author_association": "NONE",
        "body": "@phobson The original goal was simply adding a test, since I thought it was fixed and @jakirkham seemed to confim that in https://github.com/dask/dask/issues/4845 . Now, running the test manually (pytest test_base.py), I was able to trigger the error. However, the error did not occur when running as a script, including setting scheduler='multiprocessing'. Do you understand what can be the difference?\r\n\r\nAdding a failing test and marking them as a known issue seems like a good solution. After submitting this patch, I realized that there is another test directory with dataframe related test. If resubmitting this, do I add another commit on the same branch or forcefully push a change ignoring the old commit? Thanks for the feedback. I am unsure how you normally handle this in larger projects.",
        "reactions": {
            "url": "https://api.github.com/repos/dask/dask/issues/comments/1252826719/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/dask/dask/issues/comments/1252837337",
        "html_url": "https://github.com/dask/dask/pull/9506#issuecomment-1252837337",
        "issue_url": "https://api.github.com/repos/dask/dask/issues/9506",
        "id": 1252837337,
        "node_id": "IC_kwDOAbcwm85KrMfZ",
        "user": {
            "login": "phobson",
            "id": 1163939,
            "node_id": "MDQ6VXNlcjExNjM5Mzk=",
            "avatar_url": "https://avatars.githubusercontent.com/u/1163939?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/phobson",
            "html_url": "https://github.com/phobson",
            "followers_url": "https://api.github.com/users/phobson/followers",
            "following_url": "https://api.github.com/users/phobson/following{/other_user}",
            "gists_url": "https://api.github.com/users/phobson/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/phobson/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/phobson/subscriptions",
            "organizations_url": "https://api.github.com/users/phobson/orgs",
            "repos_url": "https://api.github.com/users/phobson/repos",
            "events_url": "https://api.github.com/users/phobson/events{/privacy}",
            "received_events_url": "https://api.github.com/users/phobson/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2022-09-20T19:55:03Z",
        "updated_at": "2022-09-20T19:55:03Z",
        "author_association": "MEMBER",
        "body": "@marberi no need to force-push. Add as many PR-related commits as your need to the existing and push to the same branch. Github will recognize the new commits and update the PR accordingly. When PRs in the dask project are merged, all of the commits are \"squashed\" into a single commit. ",
        "reactions": {
            "url": "https://api.github.com/repos/dask/dask/issues/comments/1252837337/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/dask/dask/issues/comments/1252839227",
        "html_url": "https://github.com/dask/dask/pull/9506#issuecomment-1252839227",
        "issue_url": "https://api.github.com/repos/dask/dask/issues/9506",
        "id": 1252839227,
        "node_id": "IC_kwDOAbcwm85KrM87",
        "user": {
            "login": "phobson",
            "id": 1163939,
            "node_id": "MDQ6VXNlcjExNjM5Mzk=",
            "avatar_url": "https://avatars.githubusercontent.com/u/1163939?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/phobson",
            "html_url": "https://github.com/phobson",
            "followers_url": "https://api.github.com/users/phobson/followers",
            "following_url": "https://api.github.com/users/phobson/following{/other_user}",
            "gists_url": "https://api.github.com/users/phobson/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/phobson/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/phobson/subscriptions",
            "organizations_url": "https://api.github.com/users/phobson/orgs",
            "repos_url": "https://api.github.com/users/phobson/repos",
            "events_url": "https://api.github.com/users/phobson/events{/privacy}",
            "received_events_url": "https://api.github.com/users/phobson/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2022-09-20T19:56:57Z",
        "updated_at": "2022-09-20T19:56:57Z",
        "author_association": "MEMBER",
        "body": "To your point about other test directories, I think dask/dataframe/tests/test_groupby.py is the most logical home for this test",
        "reactions": {
            "url": "https://api.github.com/repos/dask/dask/issues/comments/1252839227/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/dask/dask/issues/comments/1267294342",
        "html_url": "https://github.com/dask/dask/pull/9506#issuecomment-1267294342",
        "issue_url": "https://api.github.com/repos/dask/dask/issues/9506",
        "id": 1267294342,
        "node_id": "IC_kwDOAbcwm85LiWCG",
        "user": {
            "login": "ian-r-rose",
            "id": 5728311,
            "node_id": "MDQ6VXNlcjU3MjgzMTE=",
            "avatar_url": "https://avatars.githubusercontent.com/u/5728311?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/ian-r-rose",
            "html_url": "https://github.com/ian-r-rose",
            "followers_url": "https://api.github.com/users/ian-r-rose/followers",
            "following_url": "https://api.github.com/users/ian-r-rose/following{/other_user}",
            "gists_url": "https://api.github.com/users/ian-r-rose/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/ian-r-rose/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/ian-r-rose/subscriptions",
            "organizations_url": "https://api.github.com/users/ian-r-rose/orgs",
            "repos_url": "https://api.github.com/users/ian-r-rose/repos",
            "events_url": "https://api.github.com/users/ian-r-rose/events{/privacy}",
            "received_events_url": "https://api.github.com/users/ian-r-rose/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2022-10-04T16:58:01Z",
        "updated_at": "2022-10-04T16:58:01Z",
        "author_association": "MEMBER",
        "body": "add to allowlist",
        "reactions": {
            "url": "https://api.github.com/repos/dask/dask/issues/comments/1267294342/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/dask/dask/issues/comments/1273183269",
        "html_url": "https://github.com/dask/dask/pull/9506#issuecomment-1273183269",
        "issue_url": "https://api.github.com/repos/dask/dask/issues/9506",
        "id": 1273183269,
        "node_id": "IC_kwDOAbcwm85L4zwl",
        "user": {
            "login": "marberi",
            "id": 2119690,
            "node_id": "MDQ6VXNlcjIxMTk2OTA=",
            "avatar_url": "https://avatars.githubusercontent.com/u/2119690?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/marberi",
            "html_url": "https://github.com/marberi",
            "followers_url": "https://api.github.com/users/marberi/followers",
            "following_url": "https://api.github.com/users/marberi/following{/other_user}",
            "gists_url": "https://api.github.com/users/marberi/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/marberi/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/marberi/subscriptions",
            "organizations_url": "https://api.github.com/users/marberi/orgs",
            "repos_url": "https://api.github.com/users/marberi/repos",
            "events_url": "https://api.github.com/users/marberi/events{/privacy}",
            "received_events_url": "https://api.github.com/users/marberi/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2022-10-10T11:36:58Z",
        "updated_at": "2022-10-10T11:36:58Z",
        "author_association": "NONE",
        "body": "Moved this over to test_groupy.py and removed the \"np+pd\" dependencies. When originally submitting I was not aware of this subdirectory. Also, when originally submitting this request, the problem did not occur when simply running the test code. Following @phobson suggestion, I add a \"pytest.mark.xfail\" to mark that this fails. \r\n\r\n(tests are still running)",
        "reactions": {
            "url": "https://api.github.com/repos/dask/dask/issues/comments/1273183269/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    }
]