[
    {
        "url": "https://api.github.com/repos/dask/dask/issues/comments/420312957",
        "html_url": "https://github.com/dask/dask/issues/3973#issuecomment-420312957",
        "issue_url": "https://api.github.com/repos/dask/dask/issues/3973",
        "id": 420312957,
        "node_id": "MDEyOklzc3VlQ29tbWVudDQyMDMxMjk1Nw==",
        "user": {
            "login": "TomAugspurger",
            "id": 1312546,
            "node_id": "MDQ6VXNlcjEzMTI1NDY=",
            "avatar_url": "https://avatars.githubusercontent.com/u/1312546?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/TomAugspurger",
            "html_url": "https://github.com/TomAugspurger",
            "followers_url": "https://api.github.com/users/TomAugspurger/followers",
            "following_url": "https://api.github.com/users/TomAugspurger/following{/other_user}",
            "gists_url": "https://api.github.com/users/TomAugspurger/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/TomAugspurger/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/TomAugspurger/subscriptions",
            "organizations_url": "https://api.github.com/users/TomAugspurger/orgs",
            "repos_url": "https://api.github.com/users/TomAugspurger/repos",
            "events_url": "https://api.github.com/users/TomAugspurger/events{/privacy}",
            "received_events_url": "https://api.github.com/users/TomAugspurger/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2018-09-11T15:22:26Z",
        "updated_at": "2018-09-11T15:22:26Z",
        "author_association": "MEMBER",
        "body": "Is this caused by the same issue as https://github.com/dask/dask/issues/3972#issuecomment-420312790?",
        "reactions": {
            "url": "https://api.github.com/repos/dask/dask/issues/comments/420312957/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/dask/dask/issues/comments/420385704",
        "html_url": "https://github.com/dask/dask/issues/3973#issuecomment-420385704",
        "issue_url": "https://api.github.com/repos/dask/dask/issues/3973",
        "id": 420385704,
        "node_id": "MDEyOklzc3VlQ29tbWVudDQyMDM4NTcwNA==",
        "user": {
            "login": "avnovikov",
            "id": 15693459,
            "node_id": "MDQ6VXNlcjE1NjkzNDU5",
            "avatar_url": "https://avatars.githubusercontent.com/u/15693459?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/avnovikov",
            "html_url": "https://github.com/avnovikov",
            "followers_url": "https://api.github.com/users/avnovikov/followers",
            "following_url": "https://api.github.com/users/avnovikov/following{/other_user}",
            "gists_url": "https://api.github.com/users/avnovikov/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/avnovikov/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/avnovikov/subscriptions",
            "organizations_url": "https://api.github.com/users/avnovikov/orgs",
            "repos_url": "https://api.github.com/users/avnovikov/repos",
            "events_url": "https://api.github.com/users/avnovikov/events{/privacy}",
            "received_events_url": "https://api.github.com/users/avnovikov/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2018-09-11T19:03:34Z",
        "updated_at": "2018-09-11T19:17:48Z",
        "author_association": "NONE",
        "body": "Seems not, as \r\n\r\n1. passing GeoPandas as an argument for the map_partitions was working fine at least in 0.17.x. It seems that this was working for quite a while as there are numerous examples of map_partitions with geodataframes (not necessary as arguments) literally all over the net,\r\n2. passing Geo DataFrame with the from_pandas dask DataFrame (in the toy example) is still working,\r\n3. map_partitions with scattered GeoDataFrame works in toy example and I almost managed to make it working in real-life. \r\n\r\nJust for the cross-reference - my answer to your comment on probably another issue https://github.com/dask/dask/issues/3972#issuecomment-420384065",
        "reactions": {
            "url": "https://api.github.com/repos/dask/dask/issues/comments/420385704/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    }
]